apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configmap
  namespace: kube-system
data:
  traefik.toml: |
    insecureSkipVerify = true
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        regex = "^http://(.*)"
        replacement = "https://$1"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"
      
    [kubernetes]
      [kubernetes.ingressEndpoint]
        publishedService = "kube-system/traefik"

    [rancher]
    domain = "https://example.com"
      [rancher.api]
      endpoint = "https://example.com/v3"
      accessKey = "token-5hdbg"
      secretKey = "lcrgrpdtdqgfkqccp2px7p7826642nsjllrrbh74nv85hc448d4qch "

    [ping]
    entryPoint = "http"
    [api]
    entryPoint = "traefik"
