apiVersion: v1
kind: Secret
metadata:
  name: tls-cert
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress
type: kubernetes.io/tls
data:
  tls.crt: #cat cert | base64 -w0
  tls.key: #cat key | base64 -w0
